# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'FlyOrDieChristmas' do
pod 'Parse'
pod 'Alamofire'
end

target 'FlyOrDieChristmasTests' do

end

target 'FlyOrDieChristmasUITests' do

end

